// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLITiOz_oDSnqudvT0sUX5MgE6NzCK9L4',
    appId: '1:712357685322:web:0cdf1bc1c7398cb1d65eb3',
    messagingSenderId: '712357685322',
    projectId: 'flutter-for-yolov7',
    authDomain: 'flutter-for-yolov7.firebaseapp.com',
    storageBucket: 'flutter-for-yolov7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF7s8GASoAfnuX0sGbItWJ2TiQCBLsY_o',
    appId: '1:712357685322:android:08601020c13662fbd65eb3',
    messagingSenderId: '712357685322',
    projectId: 'flutter-for-yolov7',
    storageBucket: 'flutter-for-yolov7.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLITiOz_oDSnqudvT0sUX5MgE6NzCK9L4',
    appId: '1:712357685322:web:1590bb40d2baba5cd65eb3',
    messagingSenderId: '712357685322',
    projectId: 'flutter-for-yolov7',
    authDomain: 'flutter-for-yolov7.firebaseapp.com',
    storageBucket: 'flutter-for-yolov7.appspot.com',
  );

}